# Generated by Django 4.1.3 on 2022-11-03 07:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_author_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookgenre',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
